santa:
  placement:
    marker:
      dx: 0.0
      dy: 3.0
    components:
      - name: "FIRST"
        entity: HORSE
        dx: 1.0
        dy: 0.0
      - name: "SECOND"
        entity: HORSE
        dx: -1.0
        dy: 0.0
      - name: "THIRD"
        entity: HORSE
        dx: 1.0
        dy: 1.0
      - name: "FOURTH"
        entity: HORSE
        dx: -1.0
        dy: 1.0
  speed: 2
  rotationRadius: 5
  presentDropPeriod: 2
present:
  texture: "http://textures.minecraft.net/texture/47e55fcc809a2ac1861da2a67f7f31bd7237887d162eca1eda526a7512a64910"
  lootTable:
    - material: DIAMOND
      materialWeight: 1
      itemTable:
        - count: 1
          itemWeight: 1
    - material: ACACIA_LOG
      materialWeight: 4
      itemTable:
          - count: 3
            itemWeight: 1
          - count: 2
            itemWeight: 2
          - count: 1
            itemWeight: 3